---
- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Remove fail2ban default configuration file
  file:
    path: "{{ system_fail2ban_conf_file }}"
    state: absent

- name: Copy fail2ban jail configuration
  template:
    dest: "{{ system_fail2ban_conf_local_file }}"
    force: yes
    src: fail2ban/jail.local.j2
  with_items: "{{ system_fail2ban_jails }}"

- name: Start fail2ban
  service:
    name: "{{ system_fail2ban_service }}"
    state: started
    enabled: yes
