---
- name: Add groups
  group:
    name: "{{ item.name }}"
    system: "{{ item.system | default('no') }}"
  with_items: "{{ system_groups }}"

- name: Enforce disabled groups are removed
  group:
    name: "{{ item }}"
    state: absent
  with_items: "{{ system_groups_removed }}"

- name: Create per user group
  group:
    name: "{{ item.name }}"
    state: present
    system: no
  with_items: "{{ system_users }}"

- name: Add users
  user:
      name: "{{ item.name }}"
      createhome: yes
      groups: "{{ item.groups | default('') }}"
      shell: /bin/bash
      state: present
  with_items: "{{ system_users }}"

- name: Ensure disabled users are removed
  user:
    name: "{{ item }}"
    state: absent
    remove: yes
  with_items: "{{ system_users_removed }}"

- name: Add user ssh keys
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{item.1}}"
  with_subelements:
  - "{{ system_users }}"
  - authorized
